GENERAL_INPUT_PATH = "/Users/stephenlasky/Desktop/repos/deer-vision/input/caddo/"
TEST_PATH_IMG_PATH = "/Users/stephenlasky/Desktop/repos/deer-vision/images/HeathJoker.png"

FULL_IMAGE_HEIGHT = 1080
FULL_IMAGE_WIDTH = 1920

TOP = 0
TOP_RIGHT = 1
RIGHT = 2
BOT_RIGHT = 3
BOTTOM = 4
BOT_LEFT = 5
LEFT = 6
TOP_LEFT = 7

DRAG_MODE_CREATE_RECT = 0
DRAG_MODE_MODIFY_RECT = 1

# Classifications
DEER = "DR"
COYOTE = "CY"
MAN = "MN"
SQUIRREL = "SQ"
PIG = "PG"
UNLABLED = "UL"

SELECTED_BB_COLOR = "yellow"
UNSELECTED_BB_COLOR = "#FFCA0D"

TEXT_DEER = "DEER"
TEXT_COYOTE = "COYOTE"
TEXT_MAN = "MAN"
TEXT_SQUIRREL = "SQUIRREL"
TEXT_PIG = "PIG"
TEXT_UNLABELED = "Unlabeled"